name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Generate Gradle Wrapper
      run: |
        # 下载 Gradle
        wget https://services.gradle.org/distributions/gradle-8.0-bin.zip -P /tmp
        unzip -q /tmp/gradle-8.0-bin.zip -d /tmp/gradle
        export PATH=$PATH:/tmp/gradle/gradle-8.0/bin

        # 生成 Gradle Wrapper
        gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Commit Gradle Wrapper files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add gradlew gradlew.bat gradle/wrapper/
        git commit -m "Add Gradle Wrapper"
        git push origin main
